### ISSUE TITLE
Cannot read property 'info' of undefined

### ISSUE THREAD

**Issue by josecelano** [bitpay/insight#488]
```
[p2p_sync] Handle block: 0000000000093b5fc28c4fb7275859a6be4b6fc005d885214fa126acd33a96ba (allowReorgs: false)
GET /api/currency 304 1985ms

/root/nodejs/insight/node_modules/insight-bitcore-api/app/controllers/blocks.js:61
    if (!block.info) {
              ^
TypeError: Cannot read property 'info' of undefined
    at /root/nodejs/insight/node_modules/insight-bitcore-api/app/controllers/blocks.js:61:15
    at /root/nodejs/insight/node_modules/insight-bitcore-api/lib/BlockDb.js:185:30
    at /root/nodejs/insight/node_modules/insight-bitcore-api/lib/Rpc.js:88:40
    at IncomingMessage.<anonymous> (/root/nodejs/insight/node_modules/insight-bitcore-api/node_modules/bitcore/lib/RpcClient.js:189:7)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
```

**Comment by braydonf** [comment]
This is outdated.
