### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by gregtampa** [bitpay/insight#631]
To install Insight, clone the main repository:

$ git clone https://github.com/bitpay/insight.git && cd insight
Install dependencies:

$ npm install

I get error...

here is the logs: 

```
73374 info postuninstall insight-bitcore-api@0.2.11
73375 silly gentlyRm /root/insight/node_modules/insight-bitcore-api is being purged from base /root/insight
73376 verbose gentlyRm don't care about contents; nuking /root/insight/node_modules/insight-bitcore-api
73377 silly vacuum-fs purging /root/insight/node_modules/insight-bitcore-api
73378 silly vacuum-fs quitting because other entries in /root/insight/node_modules
```

```
../bignum.cc: In static member function âstatic v8::Handle<v8::Value> BigNum::Bjacobi(const int&)â:
../bignum.cc:951:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make: *** [Release/obj.target/bignum/bignum.o] Error 1
make: Leaving directory `/root/insight/node_modules/insight-bitcore-api/node_modules/bitcore/node_modules/bignum/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.16.0-38-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /root/insight/node_modules/insight-bitcore-api/node_modules/bitcore/node_modules/bignum
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Linux 3.16.0-38-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! base58-native@0.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the base58-native@0.1.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the base58-native package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls base58-native
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/insight/npm-debug.log
root@sprnde:~/insight# node insight.js
module.js:338
    throw err;
          ^
Error: Cannot find module '/root/insight/insight.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by gregtampa** [comment]
sudo add-apt-repository ppa:fkrull/deadsnakes
sudo apt-get update
sudo apt-get install python2.6
sudo update-alternatives --install /usr/bin/python python /usr/bin/python2.6 20
sudo update-alternatives --install /usr/bin/python python /usr/bin/python2.7 10

#you can switch between 2.6 & 2.7 using:
sudo update-alternatives --config python

did this to use 2.6 python as shown on https://github.com/bitpay/copay troubleshooting section.

still error outs.

```
npm ERR! base58-native@0.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the base58-native@0.1.2 install script 'node-gyp rebuild'.

```

**Comment by gregtampa** [comment]
https://github.com/TooTallNate/node-gyp/issues/363#issuecomment-32234646
reading this and tryin the solutions didn't help niether.
but this is like the same issue exit code 2 and node-gyp rebuild is the issue.

**Comment by braydonf** [comment]
This is outdated as bignum is no longer a dependency, please try with the latest: https://bitcore.io/guides/full-node
