### ISSUE TITLE
Insight  goes to 100% CPU then crashes 

### ISSUE THREAD

**Issue by mmitech** [bitpay/insight#655]
Insight  goes to 100% CPU then crashes without any error, But npm throw the next errors:

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.13.4
3 info using node@v0.10.25
4 verbose node symlink /usr/bin/node
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart insight-bitcore@0.2.7
7 info start insight-bitcore@0.2.7
8 verbose unsafe-perm in lifecycle true
9 info insight-bitcore@0.2.7 Failed to exec start script
10 verbose stack Error: insight-bitcore@0.2.7 start: `INSIGHT_PUBLIC_PATH=public node node_modules/.bin/insight-bitcore-api`
10 verbose stack Exit status 143
10 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
10 verbose stack     at EventEmitter.emit (events.js:98:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
10 verbose stack     at maybeClose (child_process.js:743:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:810:5)
11 verbose pkgid insight-bitcore@0.2.7
12 verbose cwd /root/insight
13 error Linux 3.16.0-45-generic
14 error argv "node" "/usr/local/bin/npm" "start"
15 error node v0.10.25
16 error npm  v2.13.4
17 error code ELIFECYCLE
18 error insight-bitcore@0.2.7 start: `INSIGHT_PUBLIC_PATH=public node node_modules/.bin/insight-bitcore-api`
18 error Exit status 143
19 error Failed at the insight-bitcore@0.2.7 start script 'INSIGHT_PUBLIC_PATH=public node node_modules/.bin/insight-bitcore-api'.
19 error This is most likely a problem with the insight-bitcore package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     INSIGHT_PUBLIC_PATH=public node node_modules/.bin/insight-bitcore-api
19 error You can get their info via:
19 error     npm owner ls insight-bitcore
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

when it goes to 100% (before crashing) it doesnt respond to any HTTP request and it also doesn't sync, restarting by killing the process helps, but this keeps repeating few times a day, what do you think guys ?

**Comment by mmitech** [comment]
I started using forever to solve the problem.
For users who are interested, just install forever with:  "sudo npm install forever -g", then inside insight folder start insight by: "forever start "npm start" ./"

forever will monitor insight and restart it when needed, I think even Bitpay are having problem with their live server...
