### ISSUE TITLE
Error: Could not load service "insight" as it does not support necessary methods.

### ISSUE THREAD

**Issue by posita** [bitpay/insight#698]
I'm getting this when attempting to run `bitcore-node` with Insight as a non-root user in a Docker container:

```javascript
2015-12-01T02:10:15+00:00 a2f86ba48e5e [info] insight /opt/insight/lib/node_modules/bitcore-node/lib/scaffold/start.js:64
2015-12-01T02:10:15+00:00 a2f86ba48e5e [info] insight         throw new Error(
2015-12-01T02:10:15+00:00 a2f86ba48e5e [info] insight         ^
2015-12-01T02:10:15+00:00 a2f86ba48e5e [info] insight
2015-12-01T02:10:15+00:00 a2f86ba48e5e [info] insight Error: Could not load service "insight" as it does not support necessary methods.
2015-12-01T02:10:15+00:00 a2f86ba48e5e [info] insight     at Function.setupServices (/opt/insight/lib/node_modules/bitcore-node/lib/scaffold/start.js:64:15)
2015-12-01T02:10:15+00:00 a2f86ba48e5e [info] insight     at start (/opt/insight/lib/node_modules/bitcore-node/lib/scaffold/start.js:203:31)
2015-12-01T02:10:15+00:00 a2f86ba48e5e [info] insight     at Command.<anonymous> (/opt/insight/lib/node_modules/bitcore-node/lib/cli/main.js:69:7)
2015-12-01T02:10:15+00:00 a2f86ba48e5e [info] insight     at Command.listener (/opt/insight/lib/node_modules/bitcore-node/node_modules/commander/index.js:301:8)
2015-12-01T02:10:15+00:00 a2f86ba48e5e [info] insight     at emitTwo (events.js:87:13)
2015-12-01T02:10:15+00:00 a2f86ba48e5e [info] insight     at Command.emit (events.js:172:7)
2015-12-01T02:10:15+00:00 a2f86ba48e5e [info] insight     at Command.parseArgs (/opt/insight/lib/node_modules/bitcore-node/node_modules/commander/index.js:615:12)
2015-12-01T02:10:15+00:00 a2f86ba48e5e [info] insight     at Command.parse (/opt/insight/lib/node_modules/bitcore-node/node_modules/commander/index.js:458:21)
2015-12-01T02:10:15+00:00 a2f86ba48e5e [info] insight     at Object.main (/opt/insight/lib/node_modules/bitcore-node/lib/cli/main.js:145:11)
2015-12-01T02:10:15+00:00 a2f86ba48e5e [info] insight     at Liftoff.<anonymous> (/opt/insight/lib/node_modules/bitcore-node/lib/cli/bitcore.js:31:16)
```

Raised from <https://github.com/bitpay/bitcore-node/blob/v1.0.0/lib/scaffold/start.js#L64:L66>.

The configuration directory is `/opt/insight/data/testnet`. `/opt/insight/data/testnet/bitcore-node.json` is:

```json
{
  "datadir": "/opt/insight/data/btcd",
  "network": "testnet",
  "port": 3001,
  "services": [
    "address",
    "bitcoind",
    "db",
    "insight",
    "insight-api",
    "web"
  ]
}
```

`/opt/insight/data/testnet/package.json` is:

```json
{
  "description": "A full Bitcoin node build with Bitcore",
  "repository": "https://github.com/user/project",
  "license": "MIT",
  "readme": "README.md",
  "dependencies": {
    "bitcore-lib": "^v0.13.10",
    "bitcore-node": "^1.0.0",
    "insight": "^0.7.0",
    "insight-api": "^0.3.1"
  }
}
```

**Comment by Levino** [comment]
You are probably passing in another insight object than the bitcore-node brings. Bitpay still needs to work on peer dependency configuration. Remove the insight and insight-api dependencies in the package.json.

What does your Dockerfile look like?

**Comment by braydonf** [comment]
`insight` is an unrelated npm package, `insight-ui` is what should be installed.

**Comment by posita** [comment]
*@posita smacks forehead.* :weary:

Ugh. And the insight docs were updated back in September. :disappointed: 

Just curious, but which is the correct way to set up a complete node? The [process in Insight's `README.md`](https://github.com/bitpay/insight/blob/master/README.md#getting-started), or [the one in this guide](https://bitcore.io/guides/full-node/)?

**Comment by braydonf** [comment]
Installing using https://bitcore.io/guides/full-node/ uses the bitcore module that includes all of the bitcore related modules together, which can be more convenience. The Insight README need to be updated.

**Comment by posita** [comment]
Thanks @braydonf!
