### ISSUE TITLE
uncaught exception: [RangeError: index out of range]

### ISSUE THREAD

**Issue by qishuo** [bitpay/insight#842]
[2017-12-15T13:17:10.883Z] info: ::ffff:192.168.1.150 web socket subscribe: sync
[2017-12-15T13:17:38.162Z] error: uncaught exception: [RangeError: index out of range]
[2017-12-15T13:17:38.163Z] error: RangeError: index out of range
    at checkOffset (buffer.js:700:11)
    at Buffer.readUInt32LE (buffer.js:762:5)
    at BufferReader.readUInt32LE (/home/sa/insight/mynode/node_modules/bitcore-lib/lib/encoding/bufferreader.js:81:22)
    at Transaction.fromBufferReader (/home/sa/insight/mynode/node_modules/bitcore-lib/lib/transaction/transaction.js:314:27)
    at Transaction.fromBuffer (/home/sa/insight/mynode/node_modules/bitcore-lib/lib/transaction/transaction.js:297:15)
    at InsightAPI.transactionEventHandler (/home/sa/insight/mynode/node_modules/insight-api/lib/index.js:267:30)
    at emitOne (events.js:77:13)
    at Bitcoin.emit (events.js:169:7)
    at Bitcoin._zmqTransactionHandler (/home/sa/insight/mynode/node_modules/bitcore-node/lib/services/bitcoind.js:639:10)
    at null.<anonymous> (/home/sa/insight/mynode/node_modules/bitcore-node/lib/services/bitcoind.js:713:12)

**Comment by HudsonCory** [comment]
I am having this same issue. Have you found a resolution?

**Comment by qishuo** [comment]
You need to know this
https://en.bitcoin.it/wiki/Transaction

**Comment by HudsonCory** [comment]
Care to elaborate more? maybe how you resolved the issue? or maybe point me in the right direction by explaining what this exception most likely means.

**Comment by saroar** [comment]
lol dead group no help same problem here

**Comment by gabegattis** [comment]
This is related to parsing segwit-style serialized transactions. The current master of bitcore-lib does not understand how to parse such transactions. We have a separate branch that does include such parsing logic, and we are testing it in some other projects. When it is ready, we will merge it into master. Until then, you can tell bitcoind to use the old serialization format with the -rpcserialversion flag.

**Comment by saroar** [comment]
Thanks for a reply. 
You mean start a project like this cmd? `bitcored  -rpcserialversion`

**Comment by sefo64** [comment]
Halloon
My side I work and I have a paychecknow has left you, my Blockcheini has
been besieging you, still no matter from you.
......???

thenks
S.Redjepi

2018-01-30 11:01 GMT-08:00 Saroar Khandoker <notifications@github.com>:

**Comment by sefo64** [comment]
- ABMELDEN


   - DASHBOARD <https://blockchain.info/wallet/#/home>
   - Transaktionen
   - BITCOIN <https://blockchain.info/wallet/#/btc/transactions>
   - ETHER <https://blockchain.info/wallet/#/eth/transactions>
   - BITCOIN CASH <https://blockchain.info/wallet/#/bch/transactions>
   - EXCHANGE <https://blockchain.info/wallet/#/exchange>
   - SICHERHEITSCENTER
   <https://blockchain.info/wallet/#/security-center>
   - EINSTELLUNGEN <https://blockchain.info/wallet/#/settings>
   - FAQ <https://blockchain.info/wallet/#/faq>


   - GESPONSORTE LINKS
      - [image: Inline-Bild 1] <https://api.blockchain.info/ads/out?id=91>
   -
      - Nutzungsbedingungen <https://www.blockchain.com/terms>
      -
      - Datenschiutzbestimmungen <https://www.blockchain.com/privacy>
      -
      - Über <https://www.blockchain.com/about>

BE YOUR OWN BANK.®
Senden
Empfangen
Total Balance
€12.61
YOUR BALANCES
Bitcoin1,519.06 bits
Ether0 ETHLos geht's
Bitcoin Cash0 BCHLos geht's
ALLERNEUESTE AKTIVITÄTEN
No transactions yet? No problem.Get started by adding some funds to your
wallet!LOS GEHT'S
PRICE CHARTS
ALLYEARMONTHWEEKDAY
BTC =  €8,307.02ETH =  €878.88BCH =  €1,228.94
WUSSTEN SIE SCHON?
GESENDET
January 28 @ 06:27 PM
An:
1MUN7CQPq5gJ4ebLEmrZeacU5QzTsrCWMQ
Von:
My Bitcoin Wallet
2.5 / 5
1,305.92 bits
GESENDET
January 28 @ 05:44 PM
An:
1MUN7CQPq5gJ4ebLEmrZeacU5QzTsrCWMQ
Von:
My Bitcoin Wallet
2.5 / 4
883.3 bits
GESENDET
January 28 @ 05:34 PM
An:
1MUN7CQPq5gJ4ebLEmrZeacU5QzTsrCWMQ
Von:
My Bitcoin Wallet
2.5 / 3
1,258.66 bits
GESENDET
January 28 @ 03:29 PM
An:
1MUN7CQPq5gJ4ebLEmrZeacU5QzTsrCWMQ
Von:
My Bitcoin Wallet
2.5 / 2
1,217.98 bits
GESENDET
January 28 @ 12:02 PM
An:
1MUN7CQPq5gJ4ebLEmrZeacU5QzTsrCWMQ
Von:
My Bitcoin Wallet
0.5 / 1

4 I paid for it, trying it.
Anji does not squeeze

2018-01-30 11:34 GMT-08:00 Sefadin Redjepi <redjepisefadin@gmail.com>:

**Comment by saroar** [comment]
? @sefo64

**Comment by gabegattis** [comment]
You have to pass in 1 or 0. IIRC, 1 is for new format and 0 is for old format. If you are on one of the most recent bitcoind releases, it should be new format by default.

-rpcserialversion=0

**Comment by gabegattis** [comment]
...and the rpcserialversion flag needs to be passed in to bitcoind. Passing it in to bitcored like that will not work. You need to put it in the bitcoin.conf file that is used to launch bitcoind. You should find that file in ~/.bitcore/data

For bitcoin.conf files, you don't need the "-" . Just add a line `rpcserialversion=0`.

**Comment by saroar** [comment]
@gabegattis thanks for reply do you mean i have to edit my bitcoin.config file like this 

```
server=1
testnet=1
whitelist=127.0.0.1
txindex=1
addressindex=1
timestampindex=1
spentindex=1
zmqpubrawtx=tcp://127.0.0.1:28332
zmqpubhashblock=tcp://127.0.0.1:28332
rpcallowip=127.0.0.1
uacomment=bitcore
-rpcserialversion=0
rpcuser=user
rpcpassword=passwor```

**Comment by gabegattis** [comment]
that looks correct

**Comment by parin13** [comment]
> rpcserialversion=0

worked for me!!
