### ISSUE TITLE
Error: Cannot find module '/root/insight/app/node_modules/@ionic/app-scripts'

### ISSUE THREAD

**Issue by BarneyChambers** [bitpay/insight#921]
Are there dependencies missing that I need to install before I can run `sudo npm start`. I have followed the build instructions, but when I am in the `insight` folder, I get the following error when I attempt to run `sudo npm start`

```> insight-app@ start /root/insight/app
> ionic serve

Error: Cannot find module '/root/insight/app/node_modules/@ionic/app-scripts'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/insight/app/node_modules/@ionic/cli-utils/lib/ionic-angular/app-scripts.js:9:16)
    at Generator.next (<anonymous>)
    at /root/insight/app/node_modules/@ionic/cli-utils/node_modules/tslib/tslib.js:107:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/root/insight/app/node_modules/@ionic/cli-utils/node_modules/tslib/tslib.js:103:16)
    at Object.importAppScripts (/root/insight/app/node_modules/@ionic/cli-utils/lib/ionic-angular/app-scripts.js:7:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! insight-app@ start: `ionic serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the insight-app@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by liuhuanhui** [comment]
mee to
